data_dir: /arc/project/st-cdeboer-1/nick/PLA_seq_20240313

sample_size:
    MORF: 453403
    N80: 1969695

flank:
    MORF_r1: ^GCTTTATATATCTTGTGGAAAGGACGA...ACGCGTTAAGTCGACAATCA
    MORF_r2: ^GCAGCGTATCCACATAGCGTAAAAGGAGCAACATAGTTAAGAATACCAGTCAATCTTTCACAAATTTTGTAATCCAGAGGTTGATTGTCGACTTAACGCGT...TCGTCCTTTCCACAAGATAT
    N80_r1: ^TGCATTTTTTTCACATC...GGTTACGGCTGTT
    N80_r2: ^AACAGCCGTAACC...GATGTGAAAAAAATGCA

trimmed_len:
    MORF: 24
    N80: 80

samples:
    MORF_liquid_1: CTTACCGG-TGAAGACG
    N80_liquid_1: CCGTACAT-TTCAGTTG
